#!/bin/bash
#
# Print the current CPU ang GPU temperature in a readable format.
#
cpuTemp0=$(cat /sys/devices/platform/sunxi-i2c.0/i2c-0/0-0034/temp1_input)
cpuTemp1=$(($cpuTemp0/1000))
cpuTemp2=$(($cpuTemp0/100))
cpuTempM=$(($cpuTemp2 % $cpuTemp1))

echo CPU temp"="$cpuTemp1"."$cpuTempM"'C"
